### ISSUE TITLE
Title auf "... | DEMOCRACY Browser" ändern

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/desktop#16]
<img width="558" alt="Bildschirmfoto 2022-06-07 um 18 54 37" src="https://user-images.githubusercontent.com/32302889/172439416-526bc2d8-d09f-4e5b-b007-31671ea0e7a1.png">
auf "Top 100 | DEMOCRACY Browser" ändern

**Comment by appinteractive** [comment]
Bereits geändert und vor einer Woche eingereicht. Duplikat von #3

**Comment by visionmakery** [comment]
Ist das eigentlich schon mitgeändert? 

<img width="1280" alt="Bildschirmfoto 2023-01-06 um 18 41 53" src="https://user-images.githubusercontent.com/32302889/211068300-3dff08fd-5008-4677-853a-2dbcd26dca37.png">

**Comment by appinteractive** [comment]
> Ist das eigentlich schon mitgeändert?
> 
> <img alt="Bildschirmfoto 2023-01-06 um 18 41 53" width="1280" src="https://user-images.githubusercontent.com/32302889/211068300-3dff08fd-5008-4677-853a-2dbcd26dca37.png">

Siehst du das nicht im Browser? In den previews ist es da.

**Comment by visionmakery** [comment]
👍🏻
