### ISSUE TITLE
🚀 Spenden-Alert

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/desktop#21]
Spenden-Alert blendet von unten (wie Cookies) ein, z.B. 

![Image](https://user-images.githubusercontent.com/32302889/210780630-8221a199-2841-4c78-bc20-a7091a9ec84f.png)

mit 

[finanziell](https://www.democracy-deutschland.de/#!donate)
[Spenden](https://www.paypal.com/donate/?hosted_button_id=PR4PJL4AY8RSL)
[Jetzt Nicht] schließt den Alert

**Comment by appinteractive** [comment]
@visionmakery habs nun so Implementiert:



![Image](https://user-images.githubusercontent.com/432828/210792604-6af09d8e-3f9d-49f7-ab48-d61f45d0e5da.png)


![Image](https://user-images.githubusercontent.com/432828/210792904-b9f085c1-9b3a-4a82-abee-9e2c0a02fce7.png)
