### ISSUE TITLE
🚀 Keine Sitzungswochen-Daten

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/desktop#4]
### Problem
Wenn wir noch keine Sitzungsdaten haben (so wie gerade) sollten wir noch etwas anderes anzeigen. Idealerweise ähnlich wie in der App, vgl
![IMAGE 2022-05-21 12:05:04](https://user-images.githubusercontent.com/32302889/169646598-298f8f82-9f5c-41ef-9809-712649e3e93b.jpg)
Query: https://github.com/demokratie-live/democracy-client/blob/89318e496aa066808180c56480435c2db22c7d8d/packages/mobile-app/src/screens/Bundestag/List/graphql/query/currentConferenceWeek.ts

### Solution

![](https://user-images.githubusercontent.com/32302889/79259926-c6dbbf00-7e8d-11ea-819b-19d854d39153.png)

https://github.com/demokratie-live/democracy-client/issues/1177

**Comment by appinteractive** [comment]
@ManAnRuck leider gibt der Query für "currentConferenceWeek" null zurück, daher kann ich auch keine "zukünftige" Sitzungswoche anzeigen. Woher kommen die Daten? @visionmakery

**Comment by ManAnRuck** [comment]
@appinteractive query sollte wieder funktionieren :) hatte ich hier vergessen zu erwähnen.
