### ISSUE TITLE
🐛 Browser-Suche ergibt weniger Treffer als App-Suche

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/desktop#5]
- [ ] ### Browser 🔎 "Impfpflicht"
<img width="1280" alt="Bildschirmfoto 2022-05-21 um 12 08 40" src="https://user-images.githubusercontent.com/32302889/169646759-7aa4d524-10cf-4d5d-b8ed-7e8c7cba7cf3.png">

### App 🔎 "Impfpflicht"
![IMG_8782](https://user-images.githubusercontent.com/32302889/169646835-92e59571-12a8-46cd-b3cd-833c5204e8da.PNG)

- [ ] Suche nach ProcedureID gar nicht möglich 285556
<img width="1278" alt="Bildschirmfoto 2022-06-17 um 14 39 05" src="https://user-images.githubusercontent.com/32302889/174300042-06973155-e8f0-4797-a647-31713af5e091.png">

**Comment by appinteractive** [comment]
Nutze folgenden Query @ManAnRuck (kopiert aus der alten desktop version)


```gql
query search($term: String!) {
    searchProceduresAutocomplete(term: $term) {
      procedures {
        _id
        title
        sessionTOPHeading
        procedureId
        type
        votes
        communityVotes {
          yes
          no
          abstination
          __typename
        }
        currentStatus
        voteDate
        voteResults {
          yes
          no
          abstination
          notVoted
          namedVote
          partyVotes {
            main
            __typename
          }
          __typename
        }
        subjectGroups
        __typename
      }
      autocomplete
      __typename
    }
  }
  ```

**Comment by appinteractive** [comment]
@ManAnRuck @visionmakery kann es sein, dass nur die aktuelle legeslaturperiode in diesem query mit einbezogen wird?

**Comment by appinteractive** [comment]
Oder nutzt die App evtl. `searchProcedures` (ist depricated) und nicht die neuere `searchProceduresAutocomplete`?

@ManAnRuck

**Comment by visionmakery** [comment]
Hey, habe gerade zu Analysezwecken die Browser-Version durchsuchen müssen. Dass Prozedurnummern (z.B. 284459) gar keine Treffer ergeben, geht echt gar nicht. Das sind immerhin unsere Schlüssel-IDs.

**Comment by appinteractive** [comment]
@visionmakery @ManAnRuck aus welchen Gründen nutzen wir denn nicht die gleiche Schnittstelle wie in der App?

**Comment by ManAnRuck** [comment]
Period wird noch in der app verwendet ;)
```gql
query SearchProcedures($term: String!, $period: Int!) {
  searchProceduresAutocomplete(term: $term, period: $period) {
    procedures {
      _id
      title
      procedureId
      sessionTOPHeading
      subjectGroups
      tags
      abstract
      voteDate
      votedGovernment
      submissionDate
      completed
      voted
      type
      voteResults {
        yes
        abstination
        no
        governmentDecision
      }
      communityVotes {
        yes
        abstination
        no
        total
      }
    }
    autocomplete
  }
}

```
