### ISSUE TITLE
🐛 [Typo] "DEMOCRACY Deutschland e.V". im Footer

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/desktop#6]
kleiner Typo
<img width="338" alt="Bildschirmfoto 2022-05-21 um 12 13 10" src="https://user-images.githubusercontent.com/32302889/169646931-21f6820e-6f0c-4067-b13e-5f0d9df4dcc4.png">

**Comment by appinteractive** [comment]
Done, PR offen @ManAnRuck
