### ISSUE TITLE
🚀 Neue Ergebnisdarstellung

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/desktop#9]
### Feature

- [ ] Fraktionsergebnisse wie in der App
- [x] Sunburst-Darstellung

optimale Darstellung (sogar für Namentliche Abstimmungen bis zur Einzelperson) https://observablehq.com/@kerryrodden/sequences-sunburst

**Comment by visionmakery** [comment]
mit @appinteractive besprochen >> Darstellung: "Sunburst" in Browser-Version prototypen

**Comment by appinteractive** [comment]
- Innerer Ring: Ja / Nein
- Äußerer Ring: Parteien

**Comment by appinteractive** [comment]
https://user-images.githubusercontent.com/432828/210991320-91595d66-3199-44ba-93fc-d0e5a30b8904.mov

@visionmakery habs versucht so zu lösen, da ich die SunBurst Darstellung als etwas sehr unübersichtlich empfand.

**Comment by appinteractive** [comment]
Update: 

https://user-images.githubusercontent.com/432828/211010417-2805c230-a31f-4674-ba99-da5a17e1b502.mov

**Comment by visionmakery** [comment]
Kommentar von @ManAnRuck 

"Kleine Optimierung fällt mir gerade noch ein. Wenn man den aktiven Chart Teil ein wenig Pixel größer macht, kann man auch auf dem Handy gut erkennen, was man gerade ausgewählt hat."

**Comment by appinteractive** [comment]
Ich werde mir mal s schauen was da geht.
